[build]
  publish = "public/"
  command = "NODE_ENV=production npm run build && npm run check && npm run test && npm run lint && npm run cleanup"
  functions = "server/functions/"

[[plugins]]
  package = "./cache-plugin"

[[redirects]]
  from = "/ajj"
  to = "/seanbonnette"
  status = 301

[[redirects]]
  from = "/dcfc"
  to = "/bengibbard"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
