[build]
  publish = "public/"
  command = "NODE_ENV=production npm run netlify"

[[redirects]]
  from = "/ajj"
  to = "/seanbonnette"
  status = 301

[[redirects]]
  from = "/dcfc"
  to = "/bengibbard"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
