name: Fetch YouTube Data
on: repository_dispatch

jobs:
  data:
    name: Get latest video data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout and install
        run: |
          git checkout -b fetch_data
          npm install
          git checkout package-lock.json

      - name: Fetch new data
        run: 'npm run data ${{ github.event.client_payload.artist }}'
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: 'Fetch new data for ${{ github.event.client_payload.artist }}'
          branch: fetch_data
          title: 'New Data for ${{ github.event.client_payload.artist }}'
          body: |
            Automated data fetch triggered by ${{ github.event.client_payload.type }}.
