name: Fetch YouTube Data
on:
  repository_dispatch:
  schedule:
    - cron: '0 15 * * 2,4,6'

jobs:
  data:
    name: Get latest video data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: |
          npm install
          git checkout package-lock.json

      - name: Fetch new data
        run: |
          npm run data ${{ github.event.client_payload.artist }}
          npm run data:fixtures ${{ github.event.client_payload.artist }}
          npm run build:server
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Fetch new data for ${{ github.event.client_payload.artist || 'all' }}
          branch: fetch_data
          title: New Data for ${{ github.event.client_payload.artist || 'all' }}
          body: |
            Automated data fetch triggered by ${{ github.event.client_payload.type || 'cron' }}.
