name: Seed YouTube Data to DB
on:
  push:
    branches:
      - main

jobs:
  data:
    name: Get latest video data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Use npm 7
        run: |
          npm install -g npm@7.8.0

      - name: Install
        run: |
          npm install

      - name: Seed data
        run: |
          npm run seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
